# Generated by Django 4.1.1 on 2022-11-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employeeapp',
            new_name='employeedetail',
        ),
    ]
